### PR TITLE
Title Screen Initial

### PR DESCRIPTION
**Pull request by WKFO**
## Description
Initial menu layout, no functionality yet.

## Motivation and Context
I'm working.

## How Has This Been Tested?
O_o (accurate description)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
Does this have to show up when I run the project?

**Comment by WKFO** [comment]
Not yet I suppose?

**Comment by orhun** [comment]
So, are you going to make that happen?

**Comment by WKFO** [comment]
We don't have any other scenes yet, so later, when we have them.

**Pull request merged**
